// ============================================================
// espadines.js — catálogo completo de espadines con compatibilidad
// ============================================================
export const ESPADINES_CATALOGO = [
  { codigo: "TOY43",   marcas: "Toyota, Pontiac, Scion" },
  { codigo: "TOY43R",  marcas: "Toyota, Chevrolet, GM, Holden, Isuzu, Subaru" },
  { codigo: "TOY47",   marcas: "Toyota" },
  { codigo: "TOY48",   marcas: "Toyota, Lexus" },
  { codigo: "TOY40",   marcas: "Hyundai, Kia, IX35, Sportage" },
  { codigo: "TOY2014", marcas: "Toyota VA2" },
  { codigo: "TOY38R",  marcas: "Toyota, Kia" },
  { codigo: "HU49",    marcas: "Audi, Skoda, VW" },
  { codigo: "HU58",    marcas: "BMW" },
  { codigo: "HU64",    marcas: "Mercedes Benz" },
  { codigo: "HU39",    marcas: "Mercedes Benz" },
  { codigo: "HU66",    marcas: "VW, Passat, Bora, Skoda, Audi A6" },
  { codigo: "HU83",    marcas: "Renault, Peugeot, Citroen" },
  { codigo: "HU92",    marcas: "BMW, MG" },
  { codigo: "HU100",   marcas: "Opel, Buick, Chevrolet, GMC" },
  { codigo: "HU101",   marcas: "Ford, Land Rover" },
  { codigo: "HU133",   marcas: "Fiat, Suzuki Swift, Nissan, Opel" },
  { codigo: "HU136",   marcas: "Renault" },
  { codigo: "HU162",   marcas: "VW, Skoda" },
  { codigo: "HU43",    marcas: "Opel" },
  { codigo: "HU57",    marcas: "Volvo, BYD F3" },
  { codigo: "HU134",   marcas: "Kia Venga" },
  { codigo: "HU87R",   marcas: "Opel, Subaru, Suzuki, Mazda 3.5" },
  { codigo: "HON58R",  marcas: "Honda, Opel, Isuzu, Acura" },
  { codigo: "HON66",   marcas: "Honda, Acura" },
  { codigo: "CY24",    marcas: "Chrysler 300C, Jeep, Dodge, BMW" },
  { codigo: "NSN11",   marcas: "Nissan, Subaru" },
  { codigo: "NSN14",   marcas: "Nissan" },
  { codigo: "HY22",    marcas: "Hyundai, Kia" },
  { codigo: "HY20",    marcas: "Hyundai, Kia" },
  { codigo: "HY20R",   marcas: "Hyundai, Kia" },
  { codigo: "HYN10",   marcas: "Ssangyong" },
  { codigo: "HYN14",   marcas: "Hyundai Elantra, Kia" },
  { codigo: "HYN6",    marcas: "Hyundai Elantra, Tucson, Kia Cerato" },
  { codigo: "HYN41",   marcas: "Hyundai, Kia" },
  { codigo: "MAZ24",   marcas: "Mazda" },
  { codigo: "MAZ24R",  marcas: "Mazda" },
  { codigo: "MAZ225",  marcas: "Mazda" },
  { codigo: "NEY73",   marcas: "Renault, Peugeot, Citroen" },
  { codigo: "NE72",    marcas: "Renault, Peugeot, Citroen" },
  { codigo: "DWO5",    marcas: "Chevrolet" },
  { codigo: "DAT17",   marcas: "Subaru" },
  { codigo: "YM28",    marcas: "Opel, Holden, Chevrolet" },
  { codigo: "VAC102",  marcas: "Renault, Megane, Dacia, Clio, Duster" },
  { codigo: "VA2",     marcas: "Citroen, Peugeot, Renault" },
  { codigo: "SIP22",   marcas: "Fiat" },
  { codigo: "SX9",     marcas: "Citroen Elysee" },
  { codigo: "SZ11",    marcas: "Suzuki" },
  { codigo: "GT10",    marcas: "Iveco" },
  { codigo: "MIT8",    marcas: "Mitsubishi" },
  { codigo: "MIT11",   marcas: "Mitsubishi" },
  { codigo: "FO38",    marcas: "Ford, Lincoln, Mercury" },
  { codigo: "FO21",    marcas: "Ford Mondeo" },
  { codigo: "GM39",    marcas: "Buick, Chevrolet, Oldsmobile, Pontiac, Hummer" },
  { codigo: "GM45",    marcas: "Pontiac, Holden, Commodore VE" },
  { codigo: "HU46",    marcas: "Opel, Chevrolet, Holden" },
  { codigo: "NO14",    marcas: "Isuzu, Hainan, Mazda" },
  { codigo: "NO16",    marcas: "Mitsubishi, Suzuki Alto" },
  { codigo: "NO17",    marcas: "Citroen Elysee, Picasso" },
  { codigo: "NO20",    marcas: "Land Rover" },
  { codigo: "KIA7",    marcas: "Kia" },
];
